#!/usr/bin/env bash
# Generate .github/labeler.yml from repo layout (lives next to the output).
#
# Convention:
#   - src/**, product tests, package meta → area:up
#     (every tracked path must match some area:*)
#   - test harness → area:test (`testenv/**` plus each `test/<name>` that is
#     not a product-test tree). Do not emit `!` globs into
#     any-glob-to-any-file: labeler ORs them as "not this path" and tags
#     unrelated files (CONTRIBUTING.md → area:test).
#   - Documenter → area:docs (docs/**)
#   - GitHub / repo prose → area:project-docs (README, NEWS, CONTRIBUTING,
#     SECURITY)
#   - .github/**, codecov.yml, .coderabbit.yaml → area:ci
#
# Product tests live only under the trees in `product_test_trees`. Shared
# unit / integration files stay area:up. Any other path under test/ is
# the harness (runtests, support, e2e, …).
#
# Usage:
#   ./.github/gen-labeler.sh           # write .github/labeler.yml
#   ./.github/gen-labeler.sh --check   # exit 1 if committed file is stale
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/.github/labeler.yml"

product_test_trees=(unit integration)

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  cat <<'EOF'
# AUTO-GENERATED by .github/gen-labeler.sh — do not edit by hand.
# https://github.com/actions/labeler

"area:docs":
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"

"area:project-docs":
  - changed-files:
      - any-glob-to-any-file:
          - "README.md"
          - "README.ja.md"
          - "NEWS.md"
          - "CONTRIBUTING.md"
          - "SECURITY.md"

"area:ci":
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
          - "codecov.yml"
          - ".coderabbit.yaml"

"area:test":
  - changed-files:
      - any-glob-to-any-file:
          - "testenv/**"
EOF
  shopt -s nullglob
  for entry in "${ROOT}/test/"*; do
    name="$(basename "$entry")"
    skip=false
    for tree in "${product_test_trees[@]}"; do
      [[ "$name" == "$tree" ]] && skip=true && break
    done
    [[ "$skip" == true ]] && continue
    git -C "$ROOT" check-ignore -q "test/${name}" && continue
    if [[ -d "$entry" ]]; then
      printf '          - "test/%s/**"\n' "$name"
    else
      printf '          - "test/%s"\n' "$name"
    fi
  done
  shopt -u nullglob

  cat <<'EOF'

"area:up":
  - changed-files:
      - any-glob-to-any-file:
          - "src/**"
          - "test/unit/**"
          - "test/integration/**"
          - ".gitattributes"
          - ".gitignore"
          - ".git-blame-ignore-revs"
          - ".vscode/**"
          - "LICENSE"
          - "Project.toml"
EOF
} >"$tmp"

# Every tracked file must match at least one area:* glob (minimatch-style **).
coverage_ok=1
if command -v python3 >/dev/null 2>&1; then
  if ! python3 - "$ROOT" "$tmp" <<'PY'
import re
import subprocess
import sys
from pathlib import Path

root, yml = Path(sys.argv[1]), Path(sys.argv[2])
text = yml.read_text(encoding="utf-8")
globs = re.findall(r'^\s+- "([^"]+)"\s*$', text, re.M)
if not globs:
    print("no globs in generated labeler.yml", file=sys.stderr)
    sys.exit(1)

def to_re(glob):
    i, out = 0, []
    while i < len(glob):
        if glob.startswith("**/", i):
            out.append("(?:.*/)?")
            i += 3
            continue
        if glob.startswith("**", i):
            out.append(".*")
            i += 2
            continue
        if glob[i] == "*":
            out.append("[^/]*")
            i += 1
            continue
        out.append(re.escape(glob[i]))
        i += 1
    return re.compile("^" + "".join(out) + "$")

compiled = [to_re(g) for g in globs]
files = subprocess.check_output(
    ["git", "-C", str(root), "ls-files", "-z"], text=True
).split("\0")
missing = []
for path in files:
    if not path:
        continue
    if not any(rx.match(path) for rx in compiled):
        missing.append(path)
if missing:
    print("unlabeled paths (add globs to gen-labeler.sh):", file=sys.stderr)
    for p in missing:
        print(f"  {p}", file=sys.stderr)
    sys.exit(1)
PY
  then
    coverage_ok=0
  fi
fi

mkdir -p "$(dirname "$OUT")"

if [[ "${1:-}" == "--check" ]]; then
  if [[ "$coverage_ok" -ne 1 ]]; then
    exit 1
  fi
  if [[ ! -f "$OUT" ]]; then
    echo "missing $OUT — run ./.github/gen-labeler.sh" >&2
    exit 1
  fi
  if ! diff -u "$OUT" "$tmp" >&2; then
    echo "stale labeler.yml — run ./.github/gen-labeler.sh and commit" >&2
    exit 1
  fi
  echo "labeler.yml up to date"
  exit 0
fi

if [[ "$coverage_ok" -ne 1 ]]; then
  exit 1
fi

cp "$tmp" "$OUT"
echo "wrote $OUT (base / docs / project-docs / ci / test)"
