name: Test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@v3
        with:
          version: "1.13"
      - uses: julia-actions/cache@v3
        with:
          delete-old-caches: false
      - uses: julia-actions/julia-runtest@v1

  aqua:
    name: Aqua - 1.13 - ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@v3
        with:
          version: "1.13"
      - uses: julia-actions/cache@v3
        with:
          delete-old-caches: false
      - name: Aqua.test_all (latest Aqua)
        run: ./.github/aqua-check.sh
